<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PASSWORD_INVALID</name>
   <tag></tag>
   <elementGuidId>e3c6f43a-960e-4492-b958-08950a55a546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='error']</value>
      <webElementGuid>65c9d1a8-dad9-40f4-8f84-71072a5125db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
